name: Installing 6 >
on: [push, pull_request]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for((i=1; i<=50000; i++));
          do
           curl -I 'https://www.altnews.in/' --compressed
          done

